name = "Zola Test"
description = "Testing new theme Zola Test."
license = "MIT"
homepage = "https://github.com/semanticdata/zola-test"
min_version = "0.1.0"
demo = "https://semanticdata.github.io/zola-test"

[author]
name = "Miguel Pimentel"
homepage = "https://github.com/semanticdata"
