name = "Zola Guava"
description = "Guava is a Zola theme."
license = "MIT"
homepage = "https://github.com/semanticdata/zola-guava"
min_version = "0.18.0"
demo = "https://semanticdata.github.io/zola-guava"

[author]
name = "Miguel Pimentel"
homepage = "https://github.com/semanticdata"

[original]
author = "rust-br"
homepage = "https://github.com/rust-br"
repo = "https://github.com/rust-br/dinkleberg"
