name: Zola on GitHub Pages - Taiki

on:
  # push:
  #   branches:
  #     - main 
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Install Zola
        uses: taiki-e/install-action@zola
      - name: Build Zola
        run: zola build
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  # build_and_deploy:
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Checkout main
  #       uses: actions/checkout@v3
  #     - name: Build and deploy
  #       uses: Haru-T/zola-deploy-action@v0.16.1
  #       env:
  #         PAGES_BRANCH: gh-pages
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
